#+TITLE: Deerhunt Game Rules

* Rules
  Ranges:
  - http://prntscr.com/mka8g4

  Fog of war:
  - Participants will not have access to global locations of the enemy; units will only be able to see a certain range around them.

  Melee unit:
  - Can make a single attack dealing one health point in the 3x3 grid (range 1) around them.
  - Or can make two moves in a single turn.
  - Takes two turns to duplicate/ spawn another melee unit.
  - Has one health point.
  - Has range 2 vision.

  Ranged unit:
  - Can take a single attack dealing one health point in the 5x5(-4) grid (range 2) around them.
  - Or can make a single move in a turn.
  - Takes four turns to duplicate.
  - Has one health point.
  - Has range 3 vision.

  Map and spawns:
  - Player 1 and player 2's starting squad (1 ranged unit, 1 melee unit) start in opposite, mirrored locations.
  - The map will be symmetrical about the axis which equidistantly separates player 1 and 2's spawn points.
  - After X amount of time, the map will begin to shrink.

  Winning condition and turns:
  - The game is turn-based with player 1 starting.
  - The game ends when all of the units of one player is eliminated, where the victor is the player with remaining units.

* Client Spec
  In order to make moves you will use the =Move= class.

  There are three types of moves:
  - Regular movement =Move('LEFT', 'LEFT', 'RIGHT')=
  - Attack movement =Move('ATTACK, 'RIGHT')=
    - This won't move your unit it will simply attack in that direction if valid
  - Duplicate movement =Move('DUPLICATE, 'DOWN)=
    - This will lock your unit in duplication and the unit will appear in 
      the direction specified when completed
      

  Your tick function will return a =list= of these =Move= objects and they will be
  executed in order. Failure to comply with the spec will result in =ALL= of your moves
  for that turn being ignored.
