#+TITLE: Deerhunt Game Rules

* Rules
  Whenever there is * next to a number, it means that the value will likely be tweaked as we test the game. The offensive unit, worker unit, and resources still need names.

  Ranges:
  - http://prntscr.com/mka8g4 (to be updated).

  Fog of war:
  - Participants will not have access to global locations of the enemy; units will only be able to see a certain range around them.

  Map:
  - The map will be 40x40*.
  - The map will be symmetrical about the axis which equidistantly separates player 1 and 2's spawn points.
  - There will be 5* resource hubs, 4 of which will respect the symmetry and the last placed in the center of the map.

  Resources:
  - Players have a certain number of 'resources' throughout the game.
  - Players will begin with 0* units of 'resource' each.
  - The resource hubs will become saturated after 10* units of 'resource' is collected.

  Offensive unit:
  - Can make a single attack dealing 1 health point with range 1*.
  - Or can make a single move.
  - Or it can begin to duplicate, which takes 5* turns and 1* unit of resource, and will be incapable of performing any action for this duration.
  - Has 3 health points.
  - Has range 4* vision.

  Worker unit:
  - When on a resource hub, it can take 5* turns to collect 1* unit of 'resource'.
  - These cannot duplicate.
  - When a player has vision of any opposition worker unit, they will be able to see the number of resources their opponent has.

  Spawn:
  - Each player begins with 3* workers and 1* offensive unit.

  Winning condition and turns:
  - The game is asynchronous turn-based with player 1 starting.
  - The game ends when all of the units of one player is eliminated, where the victor is the player with remaining units OR after 100* turns, where the victor is the player with the most resources. If the two players have the same amount, then player 2 wins.

* Client Spec
  In order to make moves you will use the =Move= class.

  There are three types of moves:
  - Regular movement =Move('unitid', 'LEFT', 'LEFT', 'RIGHT')=
  - Attack movement =Move('unitid', 'ATTACK, 'RIGHT')=
    - This won't move your unit it will simply attack in that direction if valid
  - Duplicate movement =Move('unitid', 'DUPLICATE, 'DOWN)=
    - This will lock your unit in duplication and the unit will appear in 
      the direction specified when completed
  - Mining movement =Move('unitid', 'MINE', 'UP')=
    - This will lock your unit into mining until the resource is gathered
      
      
  Note that only melee units may deplicate and only mining worker units may mine

  Your tick function will return a =list= of these =Move= objects and they will be
  executed in order. Failure to comply with the spec will result in =ALL= of your moves
  for that turn being ignored.
