version: '3.9'

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./deerhunt/build:/var/www/html
      - ./nginx/fullchain.pem:/etc/nginx/ssl/live/mcss.utmrobotics.com/fullchain.pem
      - ./nginx/privkey.pem:/etc/nginx/ssl/live/mcss.utmrobotics.com/privkey.pem
  web:
    build: ./server
    ports:
      - "5000:5000"
    restart: always
