version: '3.9'

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    # restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./deerhunt/build:/var/www/html
  certbot:
    image: certbot/cerbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  # web:
  #   build: ./server
  #   ports:
  #     - "5000:5000"
